name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PNPM and Install Dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
      - name: Get pnpm store directory~
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm build
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: dist/get-200-status-test.js
